version: "2.0"
services:

  mysql:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_ROOT_PASSWORD: db_root_passwd
    command:
      - "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network

  php:
    image: php:7.3-fpm
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/example.com
    volumes:
      - .:/var/www/example.com
    entrypoint:
      - php-fpm
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/example.com
    volumes_from:
      - php
    volumes:
      - ./docker-compose-config/nginx:/etc/nginx/conf.d
    links:
      - php
    ports:
      - "80:80"
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge